name: Build
on:
  workflow_call:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'
      - run: script/build
      - uses: actions/upload-artifact@v2
        with:
            name: atom-${{ runner.os }}
            path: out/
